### ISSUE TITLE
[Enigma] BitConverter

### ISSUE THREAD

**Issue by pavel-b-novikov** [mistler/nsudotnet#3]
Объясните необходимость его использования.

**Comment by mistler** [comment]
Нужно было сохранить в каком-то формате длинну IV в файл. Насколько я помню, длина может принимать значения из множества {32, 64, 128, 256} (смотрел на MSDN). Решил для простоты использовать int для хранения этого числа. Чтобы побайтово записать int в файл, нужно преобразовать его в массив байт, для этого гугл предлагает использовать BitConverter. На более низкоуровневом языке написал бы через битовые сдвиги. BitConverter позволяет преобразовать Int <=> byte[4], причем мне не надо знать в каком формате он их будет хранить.

**Comment by pavel-b-novikov** [comment]
А что такое base64 в таком случае? И зачем вам длина?

**Comment by mistler** [comment]
Поправил. Base64 это в человеко-читаемом формате, так что Key/IV в кодировке base64 не содержит символа перевода строки и можно записать их в файл каждый с новой строки. Длина не требуется. Убрал BitConverter.

**Comment by pavel-b-novikov** [comment]
Хорошо хоть сами догадались.
